name: cve-update

# Controls when the workflow will run
on:
  push: 
   branches:
    - main 

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: action\checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
    - name: Run main.py
      env:
        MY_GITHUB_TOKEN: \$
        
